on:  
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  xcframework:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CMake
        run: brew install cmake
      - name: Build XCFramework
        run: |
          python3 platforms/apple/build_xcframework.py -o build --framework_name OpenCV --dynamic
          cd build
          ls -al
      - name: Zip XCFramework
        run: cd build && zip -r OpenCV.xcframework.zip OpenCV.xcframework
      - name: Upload XCFramework
        uses: actions/upload-artifact@v3
        with:
          name: OpenCV.xcframework.zip
          path: build/*.zip
          if-no-files-found: error
